jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ1
jwt:
  header: Authorization
  tokenHead: 'Bearer '
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
  mapper-locations: classpath:mapper/*.xml,classpath:mapper2/*.xml
  typeAliasesPackage: com.xd.pre.domain,com.xd.pre.modules.myeletric.domain
pre:
  security:
    social:
      gitee:
        app-id: 663221d0507f284b2265b7b8d95a9c1293bdd5adc7b4a35c9748fd3875746e67
        app-secret: 411f5eeabb0365664fc2e82ed735ec688152127838ad145159f19c90170ebde1
        provider-id: gitee
      github:
        app-id: 0e4b224d9c629ce3f3ea
        app-secret: 31fc9751b005f5e40113fc3f07b5beae0a7dad25
        provider-id: github
      qq:
        app-id: 101715108
        app-secret: 453e1be400a9cf207fea273f0d2c6248
        provider-id: qq
      weixin:
        app-id: wx5c451c1c46ba0ff9
        app-secret: 41f76af6ab2478dccbcdd4d741cb5d02
        provider-id: weixin
  tenant:
    ignoreTenantTables:
      - sys_tenant
      - sys_menu
      - sys_user_role
      - sys_role_menu
      - sys_role_dept
      - sys_user_role
      - sys_dict_item
      - TABLES
      - COLUMNS
      - sys_job
      - my_room
      - my_area
      - my_meter
      - my_wmeter
      - my_map_user_meter
      - my_map_user_wmeter
      - my_room_tenant
      - my_tenant_his
      - my_meter_record
      - my_meter_fee
      - my_wmeter_record
      - my_wmeter_fee
      - pre_meter
      - my_product
      - product_property
      - product_signal
      - product_event
      - product_function
      - product_function_param
      - product_device
      - property_record
      - my_channel
      - my_channel_mqtt
      - my_payment
      - my_payment_detail_wx
      - sys_user_count
      - my_promotion
      - device_command
    tenantIdColumn: tenant_id
  url:
    address: http://localhost:9528
server:
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true
    io-threads: 4
    worker-threads: 20
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 3
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/saas?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
  mail:
    host: smtp.qq.com
    password: ENC(b1a/IYyqK7WL70rlA7JZxmqqoLDY2rtLvX9cNp5YWP0=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: ENC(F+SSuP2w34EywET9mD9eOzfKk2/w0AUaj1w+TVNmyj8=)
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30000ms
        min-idle: 1
    password: ''
    port: 6379
    timeout: 6000ms

uploadFileServerPathPrefix: /Users/lihaodong/Desktop/files